version: '2'
services:
    volley-app:
        image: volley
        external_links:
            - volley-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/volley
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    volley-postgresql:
        extends:
            file: postgresql.yml
            service: volley-postgresql
